services:
  - type: web
    name: rag-fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    disk:
      name: rag-data
      mountPath: /opt/render/project/src/data
